
#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of the tool.
#
TOOLNAME=hw1pass

#
# List libraries that we'll need
# We use LIBS because hw1pass is a dynamic library.
#
USEDLIBS = hw1pass.a

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common
